version: '3.7'

services:
  landingpage:
    image: omnimaker/landingpage:v0.1.0  # Versão específica
    deploy:
      mode: replicated
      replicas: 1    
      placement:
        constraints:
          - node.role == manager
      labels:
        # Traefik labels
        - traefik.enable=true
        - traefik.http.routers.landingpage.rule=Host(`omnimaker.com.br`)
        - traefik.http.routers.landingpage.entrypoints=websecure
        - traefik.http.routers.landingpage.tls.certresolver=letsencryptresolver
        - traefik.http.routers.landingpage.service=landingpage
        - traefik.http.services.landingpage.loadbalancer.server.port=3000
        
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=https://omnimaker.com.br
      - NEXT_PUBLIC_ENVIRONMENT=production
      - NEXT_PUBLIC_SW_ENABLED=true
      - NEXT_PUBLIC_PWA_ENABLED=true
    networks:
      - rede_omni1

networks:
  rede_omni1:
    name: rede_omni1
    external: true