import { PricingPlan } from "./types";

export const pricingPlans: PricingPlan[] = [
  {
    name: "Básico",
    price: "697",
    yearlyPrice: "6970",
    period: "mês",
    yearlyPeriod: "ano",
    features: [
      "Até 1.000 mensagens/mês",
      "1 WhatsApp conectado",
      "Chatbot básico",
      "Suporte por email",
    ],
    description: "Perfeito para pequenas empresas",
    buttonText: "Começar agora",
    href: "/auth/signup?plan=basic",
    isPopular: false,
  },
  {
    name: "Profissional",
    price: "997",
    yearlyPrice: "9970",
    period: "mês",
    yearlyPeriod: "ano",
    features: [
      "Até 5.000 mensagens/mês",
      "3 WhatsApp conectados",
      "IA avançada",
      "Integrações",
      "Relatórios detalhados",
      "Suporte prioritário",
    ],
    description: "Ideal para empresas em crescimento",
    buttonText: "Escolher plano",
    href: "/auth/signup?plan=pro",
    isPopular: true,
  },
  {
    name: "Enterprise",
    price: "1997",
    yearlyPrice: "19970",
    period: "mês",
    yearlyPeriod: "ano",
    features: [
      "Mensagens ilimitadas",
      "WhatsApp ilimitados",
      "IA personalizada",
      "API completa",
      "Manager dedicado",
      "SLA garantido",
    ],
    description: "Para grandes operações",
    buttonText: "Falar com vendas",
    href: "/contato",
    isPopular: false,
  },
];
